Module8 task3
htmlacademy-ecmascript/1096051-big-trip-21 pull request #14
Opened 2023-09-30 11:45 UTC by Problemon

2023-10-01 15:09 UTC, romien94 commented on src/model/offers-model.js
> +    for (const offerData of offersByType) {
правильнее будет сделать мапой, где ты сделаешь так:
.map(({title: text, ...offerData}) => ({...offerData, text}))

2023-10-01 15:09 UTC, romien94 commented on src/model/offers-model.js
> +      offer.text = offer.title;
то же самое, что и выше

2023-10-01 15:10 UTC, romien94 commented on src/model/points-model.js
> +      throw new Error(err);
эм. у тебя err - это объект. нужно вытащить из него текст и передать в конструктор

2023-10-01 15:11 UTC, romien94 commented on src/presenter/board-presenter.js
> +  #renderEmptyList = () => {
у array function нет this.

2023-10-01 15:13 UTC, romien94 commented on src/utils/utils.js
> +    isDisabled: isDisabled,
это можно записать так
component.updateElement({isDisabled, isSaving, isDeleting})

2023-10-01 15:26 UTC, romien94 requested changes
в целом, хорошо. только комменты исправь

2023-10-02 01:05 UTC, Problemon commented on src/model/offers-model.js
> +    for (const offerData of offersByType) {
Есть

2023-10-02 01:08 UTC, Problemon commented on src/model/offers-model.js
> +      offer.text = offer.title;
+

2023-10-02 01:12 UTC, Problemon commented on src/model/points-model.js
> +      throw new Error(err);
.text

2023-10-02 01:16 UTC, Problemon commented on src/utils/utils.js
> +    isDisabled: isDisabled,
Постоянно забываю

2023-10-02 01:23 UTC, merged